# profiles.yml

retail:
 target: dev
 outputs:
  dev:
    type: bigquery
    method: service-account
    keyfile: /usr/local/airflow/include/gcp/service_account.json
    project: marine-shell-446808-b3
    dataset: retail
    threads: 1
    timeout_seconds: 300
    location: US