name: SQLFluff Lint Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install SQLFluff
        run: |
          pip install sqlfluff
          pip install sqlfluff-templater-dbt

      - name: Set up DBT environment
        run: |
          mkdir -p ${{ github.workspace }}/.dbt
          echo "profiles.yml content goes here" > ${{ github.workspace }}/.dbt/profiles.yml
          # Alternatively, add the profiles.yml file to your repository and just reference it if it's there.

      - name: Run SQLFluff linting
        env:
          DBT_PROFILES_DIR: ${{ github.workspace }}/.dbt
        run: |
          sqlfluff lint models --dialect bigquery --config .sqlfluff
